# Generated by Django 6.1.1 on 2026-09-11 01:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0003_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='decisions.criterion')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='decisions.option')),
            ],
            options={
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('option', 'criterion'), name='unique_score_per_option_criterion'), models.CheckConstraint(condition=models.Q(('score__gte', Decimal('0')), ('score__lte', Decimal('10'))), name='score_between_zero_and_ten')],
            },
        ),
    ]
